### ISSUE TITLE
invalid fbp value

### ISSUE THREAD

**Issue by Linushellberg** [managed-components/facebook-pixel#2]
after running this component for a few days facebook events manager reports: "Your server is sending an invalid fbp parameters value for your event. This may be because there was an error in the parameter value."

I see this value is created here https://github.com/managed-components/facebook-pixel/blob/72d2828e17432da8c7ffed556d54e7430b00fe07/src/track.ts#L37

Did you reverse engineer the pixel code to know how to create the fbp value or how is this done? Cant find any documentation on this from facebooks side.
I reached out to facebook for more information, but they said we can not create this value on our own, the facebook pixel js must do it. So was not more help there.

**Comment by bjesus** [comment]
Hey! It's actually documented quite clearly here: https://developers.facebook.com/docs/marketing-api/conversions-api/parameters/fbp-and-fbc

**Comment by Linushellberg** [comment]
@bjesus ah yes you are right, it looks correct. 
will have to speak to facebook again then, since events manager saying we are sending incorrect values in some cases. With the official fb pixel we used before we never got this error

**Comment by bjesus** [comment]
Yeah I think we might need more input from FB side to figure this out. I'm closing this issue for now but feel free to re-open if you hear anything back!
