### ISSUE TITLE
Facebook Pixel unable to track non PageView events from Cloudflare Zaraz

### ISSUE THREAD

**Issue by aran112000** [managed-components/facebook-pixel#4]
https://github.com/managed-components/facebook-pixel/commit/7c467f8a0c7aa5f02bd59cb37ee26c8d4d5618f2#diff-fe042aba9cb2a5435bd762554856700406bbe84b5db26638604213aff4d2d6eeR66

@simonabadoiu, this change appears to have broken the ability to track custom events through into Facebook. All events now track as 'PageView' no matter what the payload is that you send via Zaraz. See the Twitter thread on this here:
https://twitter.com/AranReeks/status/1612112893167767552

**Comment by bjesus** [comment]
This actually doesn't seem to be the cause of the issue - it only sets the value to "pageview" if the action type is "Page view". However we spotted the issue being that the dashboard doesn't allow choosing different action types - it will probably be fixed later today. Thank you for reporting!

**Comment by aran112000** [comment]
Amazing, thanks so much for the quick resolution @bjesus!

**Comment by aran112000** [comment]
Can confirm this appears partially resolved. When using a Variable value it works, however, any string value typed directly within Cloudflare still tracks as a pageview within Facebook.

We've managed to solve this by creating a string variable with the value "Lead" for example, and this then works, but believe it's still a bug that you can't enter the string value directly in the "Facebook Event Name" field?

![image](https://user-images.githubusercontent.com/3313791/211799491-9e9bfb67-857b-48d7-a00d-de8b308cbc01.png)

**Comment by bjesus** [comment]
Can you include a screenshot of your complete action? Including the top bar that shows the type of the action.

**Comment by aran112000** [comment]
> Can you include a screenshot of your complete action? Including the top bar that shows the type of the action.

Sure thing @bjesus, here's the action setup:
![image](https://user-images.githubusercontent.com/3313791/212375291-956e43ff-20ca-43a2-ba3d-6e8eeece3d79.png)

Here's the setup of the Trigger if that helps too:
![image](https://user-images.githubusercontent.com/3313791/212375363-217238e4-af3d-41f0-90f7-c08256fbab1e.png)

...and here's the blocking trigger (used to ensure relevant cookie consent has been provided):
![image](https://user-images.githubusercontent.com/3313791/212375516-4dedeaf3-8737-4349-9a55-5097a557369c.png)

**Comment by aran112000** [comment]
Hey @bjesus, just checking you saw the above?

TIA

**Comment by bjesus** [comment]
@aran112000 are you still seeing this issue? I have just tested this myself and I'm able to send any event name I enter.
