### ISSUE TITLE
Pixel does not load on page

### ISSUE THREAD

**Issue by moskoweb** [managed-components/facebook-pixel#7]
Hello,

I recently added this component to Zaraz to start using it, and I noticed that the events are sent by server correctly in the settings made, but the pixel is not actually loaded on the site, it just sends the information by server.

Is there somewhere that you need to configure so that the pixel is also loaded on the website, and not just on the server? I had to put an HTML component to load the pixel.

**Comment by bjesus** [comment]
This component is meant to to load the Facebook server-side, not client-side. This is the intended behavior.

**Comment by moskoweb** [comment]
So in this case it's just Facebook API, not Facebook Pixel and API.

Why don't you add the 2?

**Comment by bjesus** [comment]
Because Managed Components main goal is to move code evaluation away from the browser.
